language: ruby
services: 
    - docker

before_install:
    - docker build -t akshayrane/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true akshayrane/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'docker-react'
    env: 'DockerReact-env'
    bucket_name: 'elasticbeanstalk-us-east-1-320518630463'
    bucket_path: 'docker-react'
    on:
        branch: master