language: generic
services: 
    - docker

before_install:
    - sudo docker build -t akshayrane/docker-react -f Dockerfile.dev .

script:
    - sudo docker run -e CI=true akshayrane/docker-react npm run test